#!/usr/bin/env python
# -*- coding: utf-8 -*-
import requests
import json
import psutil
import datetime

USER = ""
PASSWD = ""
SENDTO = ""
MESG = u"""系统监控(百分比)：
{host} {ip}
时间 {time}
内存 {mem}
SWAP {swap}
CPU {cpu}
硬盘 {disk}"""
THRESHOLD = dict(mem=(75, 85),
                 swap = (20, 30),
                 cpu = (60, 80),
                 disk = (45, 70)
                 )
TIME_FMT = '%Y-%m-%d %H:%M:%S'

def host_info():
    """Return Host name and IP"""
    import socket
    host = socket.gethostname()
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    try:
        s.connect(("baidu.com",80))
    except socket.error:
        pass
    finally:
        ip = s.getsockname()[0]
        s.close()
    return host, ip

def monitor():
    percent = {}
    # host
    percent['host'], percent['ip'] = host_info()
    # memory
    svmem = psutil.virtual_memory()
    percent['mem'] = svmem.percent
    # swap
    percent['swap'] = psutil.swap_memory().percent
    # cpu
    percent['cpu'] = psutil.cpu_percent(interval=1)
    # disk
    percent['disk'] = psutil.disk_usage('/').percent
    # time
    time = datetime.datetime.now()
    for k, v in percent.items():
        if k in ('host', 'ip'):
            continue
        alert = 0
        low, high = THRESHOLD[k]
        if low < v < high:
            alert = 1
        elif v > high:
            alert = 2
        percent[k] = str(v) + ' !'*alert
    return MESG.format(time=time.strftime(TIME_FMT), **percent)


def send_fetion(msg):
    url = "https://quanapi.sinaapp.com/fetion.php"
    data = dict(
        u=USER,
        p=PASSWD,
        to=SENDTO,
        m=msg
    )

    r = requests.post(url, data=data)

    result = json.loads(r.content)
    print result['message']

if __name__ == "__main__":
    msg = monitor()
    if '' in msg:
        print msg
        send_fetion(monitor())
