#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Scapy in enhanced IPython mode

Run as:
    sudo ./iscapy
Example:
    traceroute('www.oschina.com')
"""

import re
import sys
import scapy.all

from IPython import start_ipython

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(start_ipython(user_ns=scapy.all.__dict__))
