#!/usr/bin/env python
"Fetch explanatin from youdao dict."
import argparse
import sys
import readline
import rlcompleter

import requests
from pyquery import PyQuery as pq


def lookup(word=None):
    url = r'http://dict.youdao.com/search'
    r = requests.get(url, params={'q': word})
    d = pq(r.content)
    phrs = d('#phrsListTab > div.trans-container > ul')
    # print phrs.text()
    return d, phrs.text()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('phrase', nargs='*')
    args = parser.parse_args()
    if not args.phrase:
        while True:
            w = raw_input('\033[1;32m> \033[0m')
            if not w:
                return
            print lookup(w)[1]
    else:
        print lookup(' '.join(sys.argv[1:]))[1]


if __name__ == '__main__':
    try:
        main()
    except (EOFError, KeyboardInterrupt):
        print
        sys.exit()
